# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "e05c78f3272e92d3baca771c5a02eda2"
name = "Patch Customizer"
handle = "patch-customizer-1"
application_url = "https://paying-ds-unlock-barn.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "patch-app-testing-store.myshopify.com"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://paying-ds-unlock-barn.trycloudflare.com/auth/callback",
  "https://paying-ds-unlock-barn.trycloudflare.com/auth/shopify/callback",
  "https://paying-ds-unlock-barn.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[pos]
embedded = false
